### ISSUE TITLE
version of setuptools in pyproject.toml not working with requirements.txt file for catElmo

### ISSUE THREAD

**Issue by muhammedhunaid** [deepomicslab/TCREmbedding#1]
Hi,

Problem: installation of requirements.txt of catElmo breaking due to preshed==2.0.1 uses diskutils.msvccompiler
Environment: Python 3.8.20 (running on x86 architecture through Rosetta on M1 Mac), setuptools==61.0.0

Best,
Muhammed

**Comment by xikanfeng2** [comment]
Hi Muhammed,

Thank you for your feedback. The installation error you encountered was due to the setuptools version. We've fixed this bug and updated both our code and documentation. The installation has been successfully tested in the following environment: Python 3.8.20, setuptools 61.0.0, and Ubuntu 22.04.2 LTS. Specifically, with setuptools version 61.0.0, you can avoid this error by adding the `--no-build-isolation` flag.

We've also added the following note to our documentation:

> **Note:** If you encounter an installation issue with the message “cannot import name ‘msvccompiler’ from ‘distutils’,” please ensure that the setuptools version is either below 65.0.0 or exactly 65.0.2. Additionally, include the `--no-build-isolation` parameter when using the pip command. 

If you have any further issues, please feel free to reach out!

Thank you again for your input!

Best,
Xikang

**Comment by xikanfeng2** [comment]
> Hi,
> 
> Problem: installation of requirements.txt of catElmo breaking due to preshed==2.0.1 uses diskutils.msvccompiler Environment: Python 3.8.20 (running on x86 architecture through Rosetta on M1 Mac), setuptools==61.0.0
> 
> Best, Muhammed

Hi Muhammed,

Thank you for your feedback. The installation error you encountered was due to the setuptools version. We've fixed this bug and updated both our code and documentation. The installation has been successfully tested in the following environment: Python 3.8.20, setuptools 61.0.0, and Ubuntu 22.04.2 LTS. Specifically, with setuptools version 61.0.0, you can avoid this error by adding the `--no-build-isolation` flag.

We've also added the following note to our documentation:

> **Note:** If you encounter an installation issue with the message “cannot import name ‘msvccompiler’ from ‘distutils’,” please ensure that the setuptools version is either below 65.0.0 or exactly 65.0.2. Additionally, include the `--no-build-isolation` parameter when using the pip command. 

If you have any further issues, please feel free to reach out!

Thank you again for your input!

Best regards,
Xikang Feng
